### ISSUE TITLE
Uptime Ratio Support

### ISSUE THREAD

**Issue by pry0cc** [winebarrel/uptimerobot#2]
Hi there! I love this API, beautifully written. 

I've been looking through this code as it seems there aren't any docs in Wiki for it.

Would you suggest how I might get uptime ratio data through this? For example, "all_time_uptime_ratio" from https://uptimerobot.com/api

Thank you!

**Comment by nuheluxulu** [comment]
require 'uptimerobot'
client = UptimeRobot::Client.new(api_key: 'u956-afus321g565fghr519')
all_time_uptime_ratios = client.getMonitors["monitors"].map {|x| x["all_time_uptime_ratio"]}
friendly_names = client.getMonitors["monitors"].map {|x| x["friendly_name"]}
statuses = client.getMonitors["monitors"].map {|x| x["status"]}
